services:
  nginx:
    image: nginx:stable-alpine
    container_name: boredgames_nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/boredgames/letsencrypt:/home/boredgames/letsencrypt:ro
      - /home/boredgames/release:/home/boredgames/release:ro
    depends_on:
      - certbot
    networks:
      - boredgames-network

  certbot:
    image: certbot/certbot:latest
    container_name: boredgames_certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/boredgames/letsencrypt:/home/boredgames/letsencrypt
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :; do
        certbot renew --webroot -w /home/boredgames/letsencrypt;
        sleep 12h & wait $!;
      done;'

  redis:
    image: redis:6
    container_name: boredgames_redis
    restart: always
    volumes:
      - /home/boredgames/redis_data:/data
    command: ["redis-server", "--dir", "/data"]
    networks:
      - boredgames-network
    deploy:
      resources:
        limits:
          memory: 100M

  api:
    image: boredgames.api
    container_name: boredgames_api
    build:
      context: .
      dockerfile: BoredGames.Server/BoredGames.API/Dockerfile
    ports:
      - "5008:8080"
    restart: always
    depends_on:
      - gameserver-silo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BORED_GAMES_CORS_ORIGIN_URL=${BORED_GAMES_CORS_ORIGIN_URL}
      - BORED_GAMES_APP_BASE_URL=${BORED_GAMES_APP_BASE_URL}
      - BORED_GAMES_API_KEY=${BORED_GAMES_API_KEY}
    networks:
      - boredgames-network

  gameserver-silo:
    image: boredgames.gameserver
    build:
      context: .
      dockerfile: BoredGames.Server/BoredGames.Server.GameServer/Dockerfile
    depends_on:
      - redis
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=redis
    ports:
      - "11112-11117:11111"
      - "30001-30006:30000"
    networks:
      - boredgames-network

  database:
    image: postgres
    container_name: ${DB_SERVER}
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/data/postgres
    networks:
      - boredgames-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: ${KEYCLOAK_SERVER_NAME}
    command: start --import-realm
    environment:
      KC_HOSTNAME: ${KEYCLOAK_SERVER_NAME}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin-temp
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin-temp
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${DB_SERVER}/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin
    volumes:
      - ./.keycloak/imports:/opt/keycloak/data/import
      - ./.keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
    ports:
      - "5555:8080"
    restart: always
    networks:
      boredgames-network:
        aliases:
          - keycloak.local

networks:
  boredgames-network:
    driver: bridge

volumes:
  postgres:
