events { }

http {
    upstream boredgames_keycloak {
        server boredgames_keycloak:8080;
    }

    upstream boregames_api {
        server boregames_api:8080;
    }

    server {
        listen 80;

        server_name boredgames.keycloak.local;
        location / {
            proxy_pass http://boredgames_keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;

        server_name boregames.api.local;
        location / {
            proxy_pass http://boregames_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
