worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    # Enable Brotli
    brotli on;
    brotli_static on;
    brotli_comp_level 6;
    brotli_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    server {
        listen 80;
        listen [::]:80;

        server_name boredgames.lol www.boredgames.lol;

        location /.well-known {
            root /home/boredgames/letsencrypt;
            allow all;
        }

        location / {
            return 301 https://$host$request_uri; # Redirect all HTTP traffic to HTTPS
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name boredgames.lol www.boredgames.lol;

        ssl_certificate /etc/letsencrypt/live/boredgames.lol/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/boredgames.lol/privkey.pem;

        error_log /var/log/nginx/boredgames.lol.error.log;

        location / {
            root /home/boredgames/release/boredgames-portal;
            index index.html;
            include mime.types;
            try_files $uri $uri/ /index.html;

            # Special handling for .br files
            location ~ \.br$ {
                gzip off;
                types {}
                default_type application/octet-stream;
                add_header Content-Encoding br;
                add_header Cache-Control "public, max-age=31536000, immutable";
            }
            
            # Specifically for Unity WebGL .data.br files
            location ~ \.data\.br$ {
                gzip off;
                types {}
                default_type application/octet-stream;
                add_header Content-Encoding br;
                add_header Cache-Control "public, max-age=31536000, immutable";
            }
            
            # For .wasm.br files
            location ~ \.wasm\.br$ {
                gzip off;
                types {}
                default_type application/wasm;
                add_header Content-Encoding br;
                add_header Cache-Control "public, max-age=31536000, immutable";
            }
            
            # For .js.br files
            location ~ \.js\.br$ {
                gzip off;
                types {}
                default_type application/javascript;
                add_header Content-Encoding br;
                add_header Cache-Control "public, max-age=31536000, immutable";
            }
        }

        location /.well-known/acme-challenge {
            root /home/boredgames/letsencrypt;
            allow all;
        }

        location /api {
            proxy_pass http://boredgames_api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept';

            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
                add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept';
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }
        }
    }
}
