name: BoredGames Backend

env:
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use

on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Solution (BoredGames.API)
        run: |
          cd ./BoredGames.Server/BoredGames.API
          sudo docker build -t boredgames-api-build ./BoredGames.Server/BoredGames.API

      - name: Build Solution (BoredGames.GameServer)
        run: |
          cd ./BoredGames.Server/BoredGames.Server.GameServer
          sudo docker build -t boredgames-gameserver-build ./BoredGames.Server/BoredGames.Server.GameServer
          
  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'

      steps:
        - name: Deploy API
          run: |
            sudo docker-compose up -d --force-recreate 




