name: BoredGames Portal

on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: BoredGames.Client/BoredGames.Portal

      - name: Build with npm
        run: npm run build --prod
        working-directory: BoredGames.Client/BoredGames.Portal

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: boredgames-portal
          path: ./BoredGames.Client/BoredGames.Portal/dist
          
  deploy:
      permissions:
        contents: none
      runs-on: self-hosted
      needs: build
      environment:
        name: 'Production'

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: boredgames-portal
            path: ./boredgames-portal
            
        - name: Deploy to Vultr
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            port: ${{ secrets.PORT }}
            source: boredgames-portal/*
            target: /home/boredgames/release
            key: ${{ secrets.SSH_KEY }}


