name: BoredGames Portal

on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: BoredGames.Client/BoredGames.Portal

      - name: Build with npm
        run: npm run build --prod
          working-directory: BoredGames.Client/BoredGames.Portal

          
  deploy:
      runs-on: self-hosted
      needs: build
      environment:
        name: 'Production'

      steps:
        - name: Deploy artifacts
          uses: actions/upload-artifact@v4
          with:
            name: boredgames-portal
            path: ./BoredGames.Client/BoredGames.Portal/dist


