name: BoredGames Backend - build & deploy

env:
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use

on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inject Sentry secret into .env file
        run: |
          sed -i 's|__BORED_GAMES_SERILOG_DSN__|${{ secrets.BORED_GAMES_SERILOG_DSN }}|g' .env

      - name: Inject Keycloak client secret in appsettings.Production.json
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" BoredGames.Server/BoredGames.API/appsettings.Production.json

      - name: Inject Keycloak client secret in keycloak realm config
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" .keycloak/imports/Production/prod-realm-config.json
      
      - name: Build Solution (BoredGames.API)
        run: |
          docker build -f BoredGames.Server/BoredGames.API/Dockerfile -t boredgames-api .

      - name: Build Solution (BoredGames.GameServer)
        run: |
          docker build -f BoredGames.Server/BoredGames.Server.GameServer/Dockerfile -t boredgames-gameserver .
          
  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf *

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inject Sentry secret into .env file
        run: |
          sed -i 's|__BORED_GAMES_SERILOG_DSN__|${{ secrets.BORED_GAMES_SERILOG_DSN }}|g' .env

      - name: Inject Keycloak client secret in appsettings.Production.json
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" BoredGames.Server/BoredGames.API/appsettings.Production.json

      - name: Inject Keycloak client secret in keycloak realm config
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" .keycloak/imports/Production/prod-realm-config.json

      - name: Stop (all)
        run: |
          docker-compose down --rmi all

      - name: Deploy (all)
        run: |
          docker-compose up --scale gameserver-silo=3 -d --force-recreate 




