name: BoredGames Portal - build & deploy

on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Inject Sentry secret into .env file
        run: |
          sed -i 's|__BORED_GAMES_SERILOG_DSN__|${{ secrets.BORED_GAMES_SERILOG_DSN }}|g' .env

      - name: Inject Keycloak client secret in appsettings.Production.json
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" BoredGames.Server/BoredGames.API/appsettings.Production.json

      - name: Inject Keycloak client secret in keycloak realm config
        run: |
          sed -i "s|__KEYCLOAK_CLIENT_SECRET__|${{ secrets.KEYCLOAK_CLIENT_SECRET }}|g" .keycloak/imports/Production/prod-realm-config.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: BoredGames.Client/BoredGames.Portal

      - name: Build with npm
        run: npm run build --prod
        working-directory: BoredGames.Client/BoredGames.Portal
          
  deploy:
      runs-on: self-hosted
      needs: build
      environment:
        name: 'Production'

      steps:
      - name: Copy built files to release directory
        run: |
          rm -rf /home/boredgames/release/boredgames-portal/*
          cp -r BoredGames.Client/BoredGames.Portal/dist/* /home/boredgames/release/boredgames-portal/


